Candidates.companyName = 'SoftInovas';
system.debug(Candidates.companyName);



Candidates c1 = new Candidates();
c1.gender = 'Male';
c1.name = 'Ali';
c1.printCandidate();

Candidates c2 = new Candidates();
c2.gender = 'Male';
c2.name = 'GulAli';
c2.printCandidate();

Candidates c3 = new Candidates();
c3.gender = 'Male';
c3.name = 'BinAli';
c3.printCandidate();


Candidates c5 = new Candidates('ali', 'male');
c5.printCandidate();